## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


## Introduction to Tensores

### Creating tensors
PyTorch tensors are created using `torch.Tensor()` : https://pytorch.org/docs/stable/tensors.html

In [4]:
# Scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# Check the number of dimension of vector
vector.ndim

1

In [9]:
# Check shape of vector
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Ransom tensors

Why random tensors?

Random tensors are important because the way many naural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers - > look at data -> update random numbers -> look at data -> update random numbers`

In [23]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4882, 0.6573, 0.8981, 0.6663],
        [0.9092, 0.7045, 0.8935, 0.0699],
        [0.4449, 0.2957, 0.8265, 0.0519]])

In [25]:
random_tensor.ndim

2

In [29]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # hight, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
torch.rand(size=(3, 3))

tensor([[0.3954, 0.8539, 0.0215],
        [0.3167, 0.1028, 0.5792],
        [0.9160, 0.3056, 0.8922]])

### Zeros and ones

In [32]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [35]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
# Creating a tensor of ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [37]:
ones * random_tensor

tensor([[0.4882, 0.6573, 0.8981, 0.6663],
        [0.9092, 0.7045, 0.8935, 0.0699],
        [0.4449, 0.2957, 0.8265, 0.0519]])

In [38]:
random_tensor.dtype

torch.float32

### Creating a range and tensors-like

In [48]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [64]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # What datatype is the tensor (e.g. torch.float32) # defaults to None, which is torch.float32 or whatever datatype is passed
    device="cpu", # defaults to None, which uses the default tensor type (e.g. "cpu", "cuda" etc.)
    requires_grad=False # Whether or not to trach gradients with this tensor operation. If True, operations performed on the tensor are recorded 
    )
float_32_tensor

tensor([3., 6., 9.])

In [65]:
float_32_tensor.dtype

torch.float32

In [67]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half would also work
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [68]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [70]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [71]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [73]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2869, 0.0975, 0.8524, 0.2489],
        [0.3603, 0.1216, 0.5920, 0.4559],
        [0.2389, 0.7971, 0.9702, 0.3082]])

In [75]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2869, 0.0975, 0.8524, 0.2489],
        [0.3603, 0.1216, 0.5920, 0.4559],
        [0.2389, 0.7971, 0.9702, 0.3082]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix mulitplication

In [76]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [97]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [78]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [79]:
# Substrace and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [80]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [98]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [83]:
# Original tensor is still unchanged
# PyTorch in-built functions
tensor

tensor([1, 2, 3])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix mulitplication (dot product)

There are two main rules that performing matrix multiplication: 
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [86]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [94]:
# Matric mulitplication
torch.matmul(tensor, tensor)

tensor(14)

In [93]:
# Can also use the "@" symbol for matrix multiplication, though not reccomended
tensor @ tensor

tensor(14)

You can do matrix multiplication by hand but it's not recommended.

The in-built `torch.matmul()` method is faster.

In [89]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 796 µs, sys: 1.19 ms, total: 1.98 ms
Wall time: 1.82 ms


tensor(14)

In [90]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 141 µs, sys: 23 µs, total: 164 µs
Wall time: 149 µs


tensor(14)

### One of the most common error in deep learning (shape errors)

In [105]:
# Shapes need to be in the right way  
tensor_A = torch.tensor(
    [[1, 2],
    [3, 4],
    [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor(
    [[7, 10],
    [8, 11], 
    [9, 12]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B) # (this will error) # torch.mm is the same as torch.matmul (it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [100]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [101]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [106]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [107]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc (aggregation)

In [112]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [109]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [110]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [115]:
# Find the mean
torch.mean(x.type(torch.float32)) # won't work without floating point or complex datatype

tensor(45.)

In [116]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [118]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [120]:
# Find the position in tensor that has the minimum value with argmin() -> retirns index position of target tesnor where the minimum value occurs
x.argmin()

tensor(0)

In [121]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshape an input tensor to a defined shape
* View - return a view of an input tensor od certain shape but keep the same memory as the original tensor
* Stacking - combining mulitple tensor on top if each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [124]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [132]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [129]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [130]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [133]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [134]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [135]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [136]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [137]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [138]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [139]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [140]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [141]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [142]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]


tensor([1, 2, 3])

### PyTorch tensors & NumPy

In [143]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [144]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [145]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [146]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In  short how neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try to make better representation of the data -> (again and again and again)`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**. 

Essentially what the random seed does is "flavour" the randomness.

In [147]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7995, 0.2672, 0.6302, 0.7989],
        [0.4909, 0.7105, 0.7603, 0.0453],
        [0.4369, 0.3127, 0.8079, 0.8310]])

Tensor B:
tensor([[0.3584, 0.4340, 0.1342, 0.8880],
        [0.2176, 0.6566, 0.4154, 0.8442],
        [0.0172, 0.0843, 0.0724, 0.6461]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [148]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Move to GPU - HOWEVER this is not supported in MacOS